In [3]:
# Import TensorFlow
import tensorflow as tf
print('\n TensorFlow imported successfully!')


 TensorFlow imported successfully!


# Check TensorFlow version

In [4]:
# Print TensorFlow version
print('TensorFlow version:', tf.__version__)

TensorFlow version: 2.19.0


# Check if your are running on GPU

In [5]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

# TensorFlow Data Types

In [6]:
# TensorFlow supports various data types for tensors
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)
print('Integer tensor:', int_tensor)
print('Float tensor:', float_tensor)
print('Boolean tensor:', bool_tensor)

Integer tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Float tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Boolean tensor: tf.Tensor([ True False  True], shape=(3,), dtype=bool)


# Tensorflow as Numpy

In [7]:
# TensorFlow tensors can be converted to NumPy arrays and vice versa
import numpy as np
np_array = np.array([10, 20, 30])
tensor_from_np = tf.constant(np_array)
print('Tensor from NumPy:', tensor_from_np)
back_to_np = tensor_from_np.numpy()
print('Back to NumPy:', back_to_np)

Tensor from NumPy: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Back to NumPy: [10 20 30]


# Generate Random Data with TensorFlow

In [8]:
random_tensor = tf.random.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)
print('Random uniform tensor:\n', random_tensor)

Random uniform tensor:
 tf.Tensor(
[[5 8 6]
 [4 6 0]
 [5 2 3]], shape=(3, 3), dtype=int32)


In [9]:
normal_tensor = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
print('Random normal tensor:\n', normal_tensor)

Random normal tensor:
 tf.Tensor(
[[-0.79782194  0.1126435  -0.32691652]
 [-0.6706387  -1.123328   -0.04538625]
 [ 3.795955   -0.6909688  -1.1367378 ]], shape=(3, 3), dtype=float32)


# TensorFlow and Keras APIs

In [10]:
tf.keras.layers.Dense

keras.src.layers.core.dense.Dense

In [11]:
# Build a simple neural network using Keras API

model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(3, activation='softmax')
])
model.summary()

C:\Users\Hibatullah\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 131 (524.00 B)

 Trainable params: 131 (524.00 B)

 Non-trainable params: 0 (0.00 B)

tf.keras.__dir__()


In [13]:
[x for x in tf.keras.layers.__dir__() if not x.startswith('__')]

['TFSMLayer',
 'deserialize',
 'serialize',
 'Activation',
 'ELU',
 'LeakyReLU',
 'PReLU',
 'ReLU',
 'Softmax',
 'AdditiveAttention',
 'Attention',
 'GroupQueryAttention',
 'MultiHeadAttention',
 'Conv1D',
 'Convolution1D',
 'Conv1DTranspose',
 'Convolution1DTranspose',
 'Conv2D',
 'Convolution2D',
 'Conv2DTranspose',
 'Convolution2DTranspose',
 'Conv3D',
 'Convolution3D',
 'Conv3DTranspose',
 'Convolution3DTranspose',
 'DepthwiseConv1D',
 'DepthwiseConv2D',
 'SeparableConv1D',
 'SeparableConvolution1D',
 'SeparableConv2D',
 'SeparableConvolution2D',
 'Dense',
 'EinsumDense',
 'Embedding',
 'Identity',
 'Input',
 'InputLayer',
 'Lambda',
 'Masking',
 'Wrapper',
 'InputSpec',
 'Layer',
 'Add',
 'add',
 'Average',
 'average',
 'Concatenate',
 'concatenate',
 'Dot',
 'dot',
 'Maximum',
 'maximum',
 'Minimum',
 'minimum',
 'Multiply',
 'multiply',
 'Subtract',
 'subtract',
 'BatchNormalization',
 'GroupNormalization',
 'LayerNormalization',
 'RMSNormalization',
 'SpectralNormalization',
 '

In [14]:
[x for x in tf.keras.losses.__dir__() if not x.startswith('__')]

['Reduction',
 'deserialize',
 'get',
 'serialize',
 'Loss',
 'CTC',
 'BinaryCrossentropy',
 'BinaryFocalCrossentropy',
 'CategoricalCrossentropy',
 'CategoricalFocalCrossentropy',
 'CategoricalGeneralizedCrossEntropy',
 'CategoricalHinge',
 'Circle',
 'CosineSimilarity',
 'Dice',
 'Hinge',
 'Huber',
 'KLDivergence',
 'LogCosh',
 'MeanAbsoluteError',
 'MeanAbsolutePercentageError',
 'MeanSquaredError',
 'MeanSquaredLogarithmicError',
 'Poisson',
 'SparseCategoricalCrossentropy',
 'SquaredHinge',
 'Tversky',
 'binary_crossentropy',
 'binary_focal_crossentropy',
 'categorical_crossentropy',
 'categorical_focal_crossentropy',
 'categorical_generalized_cross_entropy',
 'categorical_hinge',
 'circle',
 'cosine_similarity',
 'ctc',
 'dice',
 'hinge',
 'huber',
 'KLD',
 'kld',
 'kullback_leibler_divergence',
 'logcosh',
 'MAE',
 'mae',
 'MAPE',
 'mape',
 'MSE',
 'mse',
 'MSLE',
 'msle',
 'poisson',
 'sparse_categorical_crossentropy',
 'squared_hinge',
 'tversky']

# Get Dummy Data 

In [15]:
# Features: 100 samples, 4 features each
X_dummy = tf.random.normal((100, 4))
# Labels: 100 samples, 3 classes (one-hot encoded)
y_dummy = tf.one_hot(tf.random.uniform((100,), minval=0, maxval=3, dtype=tf.int32), depth=3)

In [16]:
print('X_dummy shape:', X_dummy.shape)
print('y_dummy shape:', y_dummy.shape)

X_dummy shape: (100, 4)
y_dummy shape: (100, 3)


In [17]:
# Create a tf.data.Dataset
dummy_dataset = tf.data.Dataset.from_tensor_slices((X_dummy, y_dummy)).batch(16)

# Show a batch
for features, labels in dummy_dataset.take(1):
    print('Features batch shape:', features.shape)
    print('Labels batch shape:', labels.shape)

Features batch shape: (16, 4)
Labels batch shape: (16, 3)


# Keras Datasets

In [18]:
[x for x in dir(tf.keras.datasets) if x.find("__") == -1]

['boston_housing',
 'california_housing',
 'cifar10',
 'cifar100',
 'fashion_mnist',
 'imdb',
 'mnist',
 'reuters']

In [19]:
# Example: Load the Iris dataset from tf.keras.datasets (not available), so use another open dataset like MNIST
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
print('MNIST train shape:', X_train.shape, y_train.shape)
print('MNIST test shape:', X_test.shape, y_test.shape)

MNIST train shape: (60000, 28, 28) (60000,)
MNIST test shape: (10000, 28, 28) (10000,)


# class Example

mind the output shape of the output layer with the shape of y true (the labels) where None will be infered while training/ compliting 

In [ ]:
model.compile(
    optimizers="Adam",
    loss = ""
)

- ep
batch_size: size of data within the epoche